---
- hosts: localhost
  become: false
  tasks:
    - name: Ensure the requirements installed
      debug:
        msg: "{{ '' | ipaddr }}"
      ignore_errors: true
      no_log: true
      register: ipaddr

    - name: Verify Ansible meets Algo VPN requirements.
      assert:
        that:
          - ansible_version.full is version('2.7.10', '==')
          - not ipaddr.failed
        msg: >
          You must update the requirements to use this version of Algo.
          Try to run python -m pip install -U -r requirements.txt

- name: Include prompts playbook
  import_playbook: input.yml

- name: Include cloud provisioning playbook
  import_playbook: cloud.yml

- name: Include server configuration playbook
  import_playbook: server.yml
